#<% require "kitchen-sync" %>
---
driver:
  name: digital_ocean
  digitalocean_api_token: <%= ENV["DIGITALOCEAN_API_TOKEN"] %>
  ssh_keys: '<%= ENV["SSH_KEYS"] %>'
  region: nyc3

provisioner:
  name: puppet_apply
  manifests_path: manifests
  modules_path: modules
  require_chef_for_busser: true

platforms:
  - name: centos-7.0
    driver_config: 
      size: 2gb
      image: centos-7-0-x64

suites:
  - name: whoa
    provisioner:
      manifest: whoa.pp
      puppet_yum_repo: https://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm

